import Vue from 'vue'
import { Button, Tabbar, TabbarItem, Swipe, SwipeItem, Toast, Grid, GridItem, Image, Card, PullRefresh, Panel, Field, Cell, CellGroup, Lazyload, List, Tab, Tabs, ImagePreview, Divider, Loading, Tag, Switch, Stepper, NavBar, Icon, Popup} from 'vant'

Vue.use(Button)
Vue.use(Tabbar).use(TabbarItem)
Vue.use(Swipe).use(SwipeItem)
Vue.use(Toast)
Vue.use(Grid).use(GridItem)
Vue.use(Image)
Vue.use(Card)
Vue.use(PullRefresh)
Vue.use(Panel)
Vue.use(Field)
Vue.use(Cell).use(CellGroup)
Vue.use(Lazyload)
Vue.use(List)
Vue.use(Tab).use(Tabs)
Vue.use(ImagePreview)
Vue.use(Divider)
Vue.use(Loading)
Vue.use(Tag)
Vue.use(Switch)
Vue.use(Stepper)
Vue.use(NavBar)
Vue.use(Icon)
Vue.use(Popup)
